name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build fairness-indicators
      id: build-fairness-indicators
      uses: ./.github/reusable-build
      with:
        python-version: ${{ matrix.python-version }}
        upload-artifact: true

  upload_to_pypi:
    name: Upload to PyPI
    runs-on: ubuntu-latest
    if: (github.event_name == 'release' && startsWith(github.ref, 'refs/tags')) || (github.event_name == 'workflow_dispatch')
    needs: [build]
    environment:
      name: pypi
      url: https://test.pypi.org/p/ajf-test-fairness-indicators
    permissions:
      id-token: write
    steps:
      - name: Retrieve wheels
        uses: actions/download-artifact@v4.1.8
        with:
          merge-multiple: true
          path: wheels

      - name: List the build artifacts
        run: |
          ls -lAs wheels/

      - name: Upload to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1.9
        with:
          packages_dir: wheels/
          repository_url: https://test.pypi.org/legacy/
